name: Backend tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "back"

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: 'back/pom.xml'
    - name: Build app
      run: mvn -B package --file pom.xml
    - name: Run tests
      run: mvn -B test --file pom.xml
    - name: Generate report
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Tests coverage
        path: ./back/target/site/jacoco/